// Shared provider data and utilities used by ServiceDiscovery and ProviderProfile

export const ZIP_TO_CITY = {
  '60540': 'Naperville',  '60563': 'Naperville', '60564': 'Naperville', '60565': 'Naperville',
  '60515': 'Downers Grove', '60516': 'Downers Grove', '60517': 'Woodridge',
  '60521': 'Hinsdale', '60523': 'Oak Brook', '60527': 'Burr Ridge', '60559': 'Westmont',
  '60440': 'Bolingbrook', '60490': 'Bolingbrook',
  '60544': 'Plainfield', '60586': 'Plainfield',
  '60532': 'Lisle', '60148': 'Lombard',
  '60187': 'Wheaton', '60188': 'Carol Stream', '60189': 'Wheaton',
  '60126': 'Elmhurst', '60181': 'Villa Park', '60101': 'Addison',
  '60462': 'Orland Park', '60439': 'Lemont',
  '60048': 'Libertyville', '60085': 'Waukegan',
  '60025': 'Glenview', '60062': 'Northbrook',
};

// Categories with match strings for fuzzy service filtering
export const CATEGORY_LIST = [
  { label: 'Lawn Mowing',            match: 'mow' },
  { label: 'Landscaping & Design',   match: 'landscap' },
  { label: 'Tree Trimming',          match: 'tree trim' },
  { label: 'Hedge Trimming',         match: 'hedge' },
  { label: 'Leaf Removal',           match: 'leaf' },
  { label: 'Sod Installation',       match: 'sod' },
  { label: 'Mulching',               match: 'mulch' },
  { label: 'Brush Clearing',         match: 'brush' },
  { label: 'Stump Grinding',         match: 'stump' },
  { label: 'Irrigation',             match: 'irrig' },
];

// Demo provider data — shown when Supabase table is empty
export const DEMO_PROVIDERS = [
  {
    id: 'demo-1',
    email: 'greenthumb@demo.com',
    name: 'Green Thumb Pro',
    description: 'Family-owned lawn care serving Naperville and surrounding communities since 2015. We specialize in residential mowing, hedge trimming, and seasonal cleanup. Our crew is trained, insured, and treats every property like our own.',
    address: 'Naperville, IL',
    serviceAreas: ['60540', '60563', '60564', '60565'],
    services: ['Lawn Mowing', 'Hedge Trimming', 'Leaf Removal', 'Mulching'],
    yearsInBusiness: 9,
    teamSize: 4,
    equipment: '3 commercial zero-turn mowers, 2 trailers, full trimming equipment',
    licenseNumber: 'IL-GC-2015-4421',
    avgRating: 4.9,
    reviewCount: 127,
    totalJobs: 312,
    badge: 'Top Rated',
    available: true,
    portfolio: [],
  },
  {
    id: 'demo-2',
    email: 'lawnmasters@demo.com',
    name: 'Lawn Masters LLC',
    description: 'Certified landscape professionals offering full-service lawn care, aeration, seeding, and fertilization for residential and commercial properties. We use premium organic inputs and tailor programs to Chicagoland\'s cool-season turf.',
    address: 'Downers Grove, IL',
    serviceAreas: ['60515', '60516', '60517', '60521', '60523'],
    services: ['Lawn Mowing', 'Aeration & Seeding', 'Mulching', 'Landscaping & Design', 'Sod Installation'],
    yearsInBusiness: 12,
    teamSize: 6,
    equipment: '4 commercial mowers, aerator, overseeder, 2 crew trucks',
    licenseNumber: 'IL-GC-2012-8831',
    avgRating: 4.7,
    reviewCount: 84,
    totalJobs: 220,
    badge: 'Licensed & Insured',
    available: true,
    portfolio: [],
  },
  {
    id: 'demo-3',
    email: 'eliteoutdoor@demo.com',
    name: 'Elite Outdoor Services',
    description: 'Award-winning landscape design and installation firm with a portfolio spanning residential gardens to commercial campuses. From concept to completion — native plantings, hardscaping, custom irrigation systems, and full-yard transformations.',
    address: 'Oak Brook, IL',
    serviceAreas: ['60523', '60521', '60527', '60559', '60148'],
    services: ['Landscaping & Design', 'Sod Installation', 'Irrigation', 'Mulching'],
    yearsInBusiness: 7,
    teamSize: 8,
    equipment: 'Full design studio, installation crew, irrigation specialist team',
    licenseNumber: 'IL-LAND-2017-3302',
    avgRating: 4.8,
    reviewCount: 56,
    totalJobs: 145,
    badge: null,
    available: false,
    portfolio: [],
  },
  {
    id: 'demo-4',
    email: 'winterwarriors@demo.com',
    name: 'Winter Warriors',
    description: 'Chicagoland\'s most reliable yard cleanup and seasonal maintenance crew. Leaf removal, brush clearing, and stump grinding — we handle the hard stuff so your property stays clean year-round.',
    address: 'Bolingbrook, IL',
    serviceAreas: ['60440', '60490', '60544', '60586', '60532'],
    services: ['Leaf Removal', 'Brush Clearing', 'Stump Grinding'],
    yearsInBusiness: 5,
    teamSize: 3,
    equipment: '2 commercial leaf vacuums, stump grinder, chipper, dump trailer',
    licenseNumber: 'IL-GC-2019-5517',
    avgRating: 4.6,
    reviewCount: 39,
    totalJobs: 96,
    badge: 'Fast Response',
    available: true,
    portfolio: [],
  },
  {
    id: 'demo-5',
    email: 'treecareplus@demo.com',
    name: 'TreeCare Plus',
    description: 'ISA-certified arborists specializing in tree trimming, pruning, stump grinding, and brush removal. Safety-first approach with full insurance coverage for residential and commercial clients throughout Chicagoland.',
    address: 'Plainfield, IL',
    serviceAreas: ['60544', '60586', '60440', '60490', '60439'],
    services: ['Tree Trimming', 'Stump Grinding', 'Brush Clearing', 'Hedge Trimming'],
    yearsInBusiness: 15,
    teamSize: 5,
    equipment: '60-ft bucket truck, stump grinder, wood chipper, hand climbing gear',
    licenseNumber: 'IL-ARBORIST-2009-1144',
    avgRating: 4.5,
    reviewCount: 62,
    totalJobs: 180,
    badge: 'Certified Arborist',
    available: true,
    portfolio: [],
  },
  {
    id: 'demo-6',
    email: 'seasonalpros@demo.com',
    name: 'Seasonal Pros',
    description: 'Full-service seasonal maintenance — spring cleanup, summer mowing plans, fall overseeding, and winter prep. One call covers your whole year. Eco-friendly inputs available for all services.',
    address: 'Lisle, IL',
    serviceAreas: ['60532', '60517', '60540', '60563', '60516'],
    services: ['Lawn Mowing', 'Leaf Removal', 'Mulching', 'Aeration & Seeding'],
    yearsInBusiness: 8,
    teamSize: 5,
    equipment: '3 commercial mowers, aerator, overseeder, leaf vacuum',
    licenseNumber: 'IL-GC-2016-7724',
    avgRating: 4.8,
    reviewCount: 103,
    totalJobs: 278,
    badge: 'Eco-Friendly',
    available: true,
    portfolio: [],
  },
  {
    id: 'demo-7',
    email: 'greenacre@demo.com',
    name: 'GreenAcre Irrigation',
    description: 'Irrigation design, installation, and repair for residential yards. Smart controller upgrades, seasonal startup/shutdown packages, and backflow testing. Serving DuPage and Kane counties.',
    address: 'Wheaton, IL',
    serviceAreas: ['60187', '60188', '60148', '60126', '60101'],
    services: ['Irrigation', 'Landscaping & Design', 'Sod Installation'],
    yearsInBusiness: 11,
    teamSize: 4,
    equipment: 'Full irrigation truck, smart controller inventory, pipe threading tools',
    licenseNumber: 'IL-IRRIG-2013-9981',
    avgRating: 4.7,
    reviewCount: 48,
    totalJobs: 130,
    badge: null,
    available: true,
    portfolio: [],
  },
  {
    id: 'demo-8',
    email: 'sodsquad@demo.com',
    name: 'Sod Squad Inc.',
    description: 'Specialist in sod installation and lawn restoration. We prep the base, grade for drainage, lay premium Kentucky Bluegrass or Tall Fescue sod, and leave you with a thick, green lawn — guaranteed.',
    address: 'Bolingbrook, IL',
    serviceAreas: ['60440', '60490', '60544', '60532', '60439'],
    services: ['Sod Installation', 'Lawn Mowing', 'Mulching'],
    yearsInBusiness: 6,
    teamSize: 4,
    equipment: 'Sod cutter, roller, grading tools, delivery truck',
    licenseNumber: 'IL-GC-2018-6603',
    avgRating: 4.6,
    reviewCount: 33,
    totalJobs: 88,
    badge: null,
    available: false,
    portfolio: [],
  },
];

// Normalize a Supabase provider_profiles row to the standard display shape
export function normalize(p) {
  return {
    id:              p.id || p.email || '',
    email:           p.email || '',
    name:            p.business_name || p.name || 'Unknown Provider',
    description:     p.description || '',
    address:         p.address || '',
    services:        p.services_offered || p.services || [],
    serviceAreas:    p.service_areas || p.serviceAreas || [],
    yearsInBusiness: Number(p.years_in_business || p.yearsInBusiness || 0),
    teamSize:        Number(p.team_size || p.teamSize || 1),
    equipment:       p.equipment || '',
    licenseNumber:   p.license_number || p.licenseNumber || '',
    portfolio:       Array.isArray(p.portfolio) ? p.portfolio : [],
    totalJobs:       Number(p.total_jobs || p.totalJobs || 0),
    avgRating:       Number(p.avg_rating || p.avgRating || 0),
    reviewCount:     Number(p.review_count || p.reviewCount || 0),
    badge:           p.badge || null,
    available:       p.available ?? true,
  };
}
